[InstallShield Silent]
Version=v7.00
File=Response File
[File Transfer]
OverwrittenReadOnly=NoToAll
[{C19E8090-9BBB-4ACF-8C83-D33B4EEA40F4}-DlgOrder]
Dlg0={C19E8090-9BBB-4ACF-8C83-D33B4EEA40F4}-SetupType2-0
Count=4
Dlg1={C19E8090-9BBB-4ACF-8C83-D33B4EEA40F4}-SdComponentTree-0
Dlg2={C19E8090-9BBB-4ACF-8C83-D33B4EEA40F4}-SdStartCopy2-0
Dlg3={C19E8090-9BBB-4ACF-8C83-D33B4EEA40F4}-SdFinish-0
[{C19E8090-9BBB-4ACF-8C83-D33B4EEA40F4}-SetupType2-0]
Result=303
[{C19E8090-9BBB-4ACF-8C83-D33B4EEA40F4}-SdComponentTree-0]
szDir=C:\Program Files (x86)\Hamilton\
DefaultFeature-type=string
DefaultFeature-count=1
DefaultFeature-0=DefaultFeature\Install_DB
Component-type=string
Component-count=1
Component-0=DefaultFeature
Result=1
[{C19E8090-9BBB-4ACF-8C83-D33B4EEA40F4}-SdStartCopy2-0]
Result=1
[Application]
Name=HxAdditionalInstaller
Version=1.00.0000
Company=HAMILTON
Lang=0009
[{C19E8090-9BBB-4ACF-8C83-D33B4EEA40F4}-SdFinish-0]
Result=1
bOpt1=0
bOpt2=0
