# Make binary_codec importable as a Python package
from .hxcfgfile_codec import (
    detect_format,
    parse_binary,
    parse_text,
    build_binary,
    build_text,
    read_hxcfg_file,
    parse_hxcfg_keyvalue,
    binary_to_text,
    text_to_binary,
    roundtrip_test,
    HxCfgFileModel,
    HxParsSection,
    ActivityDataSection,
    BinaryReader,
    BinaryWriter,
)

__all__ = [
    'detect_format',
    'parse_binary',
    'parse_text',
    'build_binary',
    'build_text',
    'read_hxcfg_file',
    'parse_hxcfg_keyvalue',
    'binary_to_text',
    'text_to_binary',
    'roundtrip_test',
    'HxCfgFileModel',
    'HxParsSection',
    'ActivityDataSection',
    'BinaryReader',
    'BinaryWriter',
]
